#!/bin/bash

# Remove files generated by CMake
rm -rf CMakeCache.txt cmake_install.cmake Makefile CMakeFiles 

echo '-------------------------------------'
echo
echo '   Cleaned!'
echo 
echo '-------------------------------------'

